### ISSUE TITLE
Read/create submissions from web form

### ISSUE THREAD

**Issue by childss** [cyrusinnovation/CodeTestBotServer#49]
There should be an option to read incoming emails from an inbox and automatically create submissions from them.

* If email has attachment, treat as submission:
  * Read email address and name from the `from` field.
  * Parse email body as the `email_text` field.
  * Read attachment as the zipfile (and upload).
* If email does not have any attachments, mark as ignored or maybe flag for review by a human.

For the first pass, also mark emails with multiple attachments as needing a human. With #8 we could just make them all attachments to the submission model.

**Comment by AlabamaMike** [comment]
We decided to go away from using email as a submission channel in favor of a web form.  The card title has been updated to reflect this decision.
